cargo-features = ["edition"]
[package]
name = "fibonacci-wasm"
version = "0.1.0"
edition = '2018'
license = "MIT"
description = "Fibonacci Example In Wasm"
repository = ""
authors = ["Shady Khalifa <shekohex@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[features]
default-features = ["wee_alloc"]

[profile.release]
debug = false
lto = true

[dependencies]
cfg-if = "0.1.5"
wasm-bindgen = "0.2"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.5", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.2", optional = true }
